## Updating mappings and re-indexing

PUT reports
Content-Type: application/json

{
	"mappings": {
		"properties": {
				"created": {
					"type": "date"
				},
				"email": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				},
				"frequency": {
					"type": "long"
				},
				"lastNotified": {
					"type": "date"
				},
				"name": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				},
				"nextNotification": {
					"type": "date"
				},
				"query": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				}
			}
	}
}

###
POST /_reindex
Content-Type: application/json

{
	"source": {
		"index": "reports_v2"
	},
	"dest": {
		"index": "reports"
	}
}

###

# Scripting in elastic (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-walkthrough.html)
POST items/_update_by_query

{
  "script": {
    "source": """
      ctx._source.created = '2001-01-01T00:00:00+0000';
      ctx._source.lastScraped = '2001-01-01T00:00:00+0000';
    """
  },
  "query": {
    "match_all": {}
  }
}

####

# MAPPING

{
  "mapping": {
    "_doc": {
      "properties": {
        "created": {
          "type": "date"
        },
        "description": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "lastScraped": {
          "type": "date"
        },
        "photoUrl": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "price": {
          "type": "long"
        },
        "published": {
          "type": "date"
        },
        "query": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "title": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 512
            }
          }
        },
        "url": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 2083
            }
          }
        }
      }
    }
  }
}
