#!/bin/bash

COMMAND="$1"
ARGS="${@:2}"

__usage="
Usage: toolkit [COMMAND] [COMMAND OPTIONS]

Command:
  composer                     Runs composer (prestissimo) in a docker container
  cli                          Runs console of the api application

Command Options:
Are specific to each command.
"

case ${COMMAND} in
    composer )
        docker run --rm -it -v $PWD:/app -u $(id -u):$(id -g) \
            clevyr/prestissimo \
            ${ARGS} \
        ;;
    cli )
            docker exec -it api ./app/bin/console ${ARGS}
        ;;
    * )
        echo "$__usage"
esac


