#!/bin/bash

COMMAND="$1"
ARGS="${@:2}"

__usage="
Usage: toolkit [COMMAND] [COMMAND OPTIONS]

Command:
  reload-sdk                   Updates the local version of the banot-php SDK

Command Options:
Are specific to each command.
"

case ${COMMAND} in
    reload-sdk )
        rm -rf ./vendor/banot/
        composer update banot/banot-php --ignore-platform-reqs
        ;;
    * )
        echo "$__usage"
esac


